# Start from the official Golang image to create a build artifact.
FROM golang:1.18 as builder

# Set the working directory inside the container.
WORKDIR /app

# Copy the go source files.
COPY server.go .

# Disable CGO and build the server binary.
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /server server.go

# Use a small image to run the server.
# Alpine is chosen for its small size and compatibility.
FROM alpine:latest

# Copy the server binary from the builder stage.
COPY --from=builder /server /server

# Command to run the executable.
CMD ["/server"]

